# Generated by Django 3.2 on 2023-11-29 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20231129_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='genero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.genero', verbose_name='Tipo de usuario'),
        ),
    ]
