# Generated by Django 3.2 on 2023-11-29 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercarrera',
            name='tipo_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.tipouser', verbose_name='Tipo de usuario'),
        ),
        migrations.AddField(
            model_name='usercarrera',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='barrio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campus.barrio', verbose_name='Barrio'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campus.ciudad', verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campus.pais', verbose_name='País'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campus.provincia', verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campus.campus', verbose_name='Campus'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campus.facultad', verbose_name='Facultad'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campus.programa', verbose_name='Programa'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='universidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campus.universidad', verbose_name='Universidad'),
        ),
    ]
